src/Entity/Reponses.php
<?php

namespace App\Entity;

use App\Repository\ReponsesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReponsesRepository::class)
 */
class Reponses
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $label;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_correct;

    /**
     * @ORM\ManyToOne(targetEntity=Question::class, inversedBy="reponses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $question;

    /**
     * @ORM\OneToMany(targetEntity=History::class, mappedBy="response")
     */
    private $histories;

    public function __construct()
    {
        $this->histories = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getIsCorrect(): ?bool
    {
        return $this->is_correct;
    }

    public function setIsCorrect(bool $is_correct): self
    {
        $this->is_correct = $is_correct;

        return $this;
    }

    public function getQuestion(): ?Question
    {
        return $this->question;
    }

    public function setQuestion(?Question $question): self
    {
        $this->question = $question;

        return $this;
    }

    /**
     * @return Collection|History[]
     */
    public function getHistories(): Collection
    {
        return $this->histories;
    }

    public function addHistory(History $history): self
    {
        if (!$this->histories->contains($history)) {
            $this->histories[] = $history;
            $history->setResponse($this);
        }

        return $this;
    }

    public function removeHistory(History $history): self
    {
        if ($this->histories->removeElement($history)) {
            // set the owning side to null (unless already changed)
            if ($history->getResponse() === $this) {
                $history->setResponse(null);
            }
        }

        return $this;
    }

}

src/Entity/Session.php
<?php

namespace App\Entity;

use App\Repository\SessionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=SessionRepository::class)
 */
class Session
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\OneToMany(targetEntity=User::class, mappedBy="session")
     */
    private $user;

    /**
     * @ORM\Column(type="integer")
     */
    private $nb_place;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(User $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
            $user->setSession($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->user->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getSession() === $this) {
                $user->setSession(null);
            }
        }

        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nb_place;
    }

    public function setNbPlace(int $nb_place): self
    {
        $this->nb_place = $nb_place;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="date")
     */
    private $birth_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tokenMail;

    /**
     * @ORM\Column(type="integer" , nullable=true)
     */
    private $fail;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_attempt;

    /**
     * @ORM\Column(type="string",length=450 ,nullable=true)
     */
    private $discord_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tokenDiscord;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_try;

    /**
     * @ORM\ManyToOne(targetEntity=Session::class, inversedBy="user")
     */
    private $session;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $imgDiscord;

    /**
     * @ORM\OneToOne(targetEntity=History::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $history;

    /**
     * @ORM\OneToMany(targetEntity=History::class, mappedBy="user")
     */
    private $histories;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $username_discord;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Admis;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $background_url;

    public function __construct()
    {
        $this->histories = new ArrayCollection();
    }




    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getTokenMail(): ?string
    {
        return $this->tokenMail;
    }

    public function setTokenMail(?string $tokenMail): self
    {
        $this->tokenMail = $tokenMail;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFail()
    {
        return $this->fail;
    }

    /**
     * @param mixed $fail
     */
    public function setFail($fail): void
    {
        $this->fail = $fail;
    }


    public function getLastAttempt(): ?\DateTimeInterface
    {
        return $this->last_attempt;
    }

    public function setLastAttempt(?\DateTimeInterface $last_attempt): self
    {
        $this->last_attempt = $last_attempt;

        return $this;
    }

    public function getDiscordId(): ?string
    {
        return $this->discord_id;
    }

    public function setDiscordId(?string $discord_id): self
    {
        $this->discord_id = $discord_id;

        return $this;
    }

    public function getTokenDiscord(): ?string
    {
        return $this->tokenDiscord;
    }

    public function setTokenDiscord(?string $tokenDiscord): self
    {
        $this->tokenDiscord = $tokenDiscord;

        return $this;
    }

    public function getNbTry(): ?int
    {
        return $this->nb_try;
    }

    public function setNbTry(?int $nb_try): self
    {
        $this->nb_try = $nb_try;

        return $this;
    }

    /**
     * @return bool
     */
    public function canParticipate(): bool
    {
        $atmDate = new \DateTime('now');
        if($this->getLastAttempt() != null){
            $lastAttempt = clone $this->getLastAttempt();
            return date_modify($lastAttempt,'+ 24 hours') < $atmDate;
        }
        return true;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(?Session $session): self
    {
        $this->session = $session;

        return $this;
    }

    public function getImgDiscord(): ?string
    {
        return $this->imgDiscord;
    }

    public function setImgDiscord(?string $imgDiscord): self
    {
        $this->imgDiscord = $imgDiscord;

        return $this;
    }
    public function canSignupToSession(){
        $countBadResponses = 0;
        foreach ($this->getHistories() as $history) {
            if (!$history->getResponse()->getIsCorrect()) {
                $countBadResponses++;
            }
        }
        return $countBadResponses <= 3;
    }

    /**
     * @return Collection|History[]
     */
    public function getHistories(): Collection
    {
        return $this->histories;
    }

    public function addHistory(History $history): self
    {
        if (!$this->histories->contains($history)) {
            $this->histories[] = $history;
            $history->setUser($this);
        }

        return $this;
    }

    public function removeHistory(History $history): self
    {
        if ($this->histories->removeElement($history)) {
            // set the owning side to null (unless already changed)
            if ($history->getUser() === $this) {
                $history->setUser(null);
            }
        }

        return $this;
    }

    public function getUsernameDiscord(): ?string
    {
        return $this->username_discord;
    }

    public function setUsernameDiscord(?string $username_discord): self
    {
        $this->username_discord = $username_discord;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getAdmis(): ?bool
    {
        return $this->Admis;
    }

    public function setAdmis(?bool $Admis): self
    {
        $this->Admis = $Admis;

        return $this;
    }

    public function getBackgroundUrl(): ?string
    {
        return $this->background_url;
    }

    public function setBackgroundUrl(?string $background_url): self
    {
        $this->background_url = $background_url;

        return $this;
    }

}

src/Form/SessionType.php
<?php

namespace App\Form;

use App\Entity\Session;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\DateTime;

class SessionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', DateTimeType::class, [
                'widget' => 'single_text',

            ])
            ->add('nb_place', null, [
                'label' => 'Nombre de place'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Session::class,
        ]);
    }
}

src/Controller/SessionController.php
<?php

namespace App\Controller;

use App\Entity\Session;
use App\Form\Session1Type;
use App\Repository\SessionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/session')]
class SessionController extends AbstractController
{
    #[Route('/', name: 'session_index', methods: ['GET'])]
    public function index(SessionRepository $sessionRepository): Response
    {
        return $this->render('session/index.html.twig', [
            'sessions' => $sessionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'session_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $session = new Session();
        $form = $this->createForm(Session1Type::class, $session);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($session);
            $entityManager->flush();

            return $this->redirectToRoute('session_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('session/new.html.twig', [
            'session' => $session,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'session_show', methods: ['GET'])]
    public function show(Session $session): Response
    {
        return $this->render('session/show.html.twig', [
            'session' => $session,
        ]);
    }

    #[Route('/{id}/edit', name: 'session_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Session $session, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(Session1Type::class, $session);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('session_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('session/edit.html.twig', [
            'session' => $session,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'session_delete', methods: ['POST'])]
    public function delete(Request $request, Session $session, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$session->getId(), $request->request->get('_token'))) {
            $entityManager->remove($session);
            $entityManager->flush();
        }
        return $this->redirectToRoute('session_index', [], Response::HTTP_SEE_OTHER);
    }


}

templates/session/_delete_form.html.twig
<form method="post" action="{{ path('session_delete', {'id': session.id}) }}" onsubmit="return confirm('Êtes-vous sûr de supprimer cettes session ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ session.id) }}">
    <button class="btn btn-danger ">Delete</button>
</form>

templates/session/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/session/admitUser.html.twig
{% extends 'main/index.html.twig' %}

{% block title %}Edit Session{% endblock %}

{% block content %}
    <h1>Admission de  l'utilisateur : {{ user.username }}</h1>

    <form action="{{ path('session_admitted', {'id' : user.id}) }}" method="post">
        <label for="comment">Commentaire</label>
        <textarea type="" id="comment" maxlength="1000" name="comment"> </textarea>
        <label for="admitted">Resultat : </label>
        <input type="radio" name="admit" value="admitted" id="admitted">
        <label for="admitted">Admis </label>
        <input type="radio" name="admit" value="refused" id="refused">
        <label for="refused">Refusé</label>
        <button type="submit" onclick="return confirm('Êtes vous sûr de vouloir confirmer ?')">Envoyer </button>
    </form>
{% endblock %}

templates/session/available_list_session_users.html.twig
{% extends 'main/index.html.twig' %}

{% block title %}Liste des Sessions : {% endblock %}

{% block content %}
    {% for user in users_session %}
        <div>
            {{ user.username }}
            <a href="{{ path('user_history', {'id': user.id}) }}">Voir son qcm</a>
            Discord : <a href="discord://discord.com/users/{{ user.discordId }}">{{ user.usernameDiscord }}</a>
            <a href="{{ path('session_admitted', {'id' : user.id}) }}">Admission </a>
            <a href="{{ user.backgroundUrl }}">Lien du background</a>
        </div>
    {% endfor %}

{% endblock %}

templates/session/available_session_user.html.twig
{% extends 'main/index.html.twig' %}

{% block title %}Liste des Sessions : {% endblock %}

{% block content %}
    <h1 class="text-center">Sessions disponibles </h1>
    {% for message in app.flashes('warning') %}
        <div class="flash-success">
            <img src="https://c.tenor.com/iPPLJM-iQ-8AAAAC/julien-lepers-c-est-non.gif" height="100px" alt="">
            {{ message }}
        </div>
    {% endfor %}
    {% if app.user.discordId %}
        <div class="row">
            {% for session in sessions %}
{#                {% if session.date >  %}#}
{#                    #}
{#                {% endif %}#}
                <div class="card col-6" style="width: 18rem;margin-right: 20px;">
                    <img class="card-img-top" src="{{ asset('assets/img/session_img.png') }}" alt="Card image cap">
                    <div class="card-body ">
                        <h5 class="card-title">Session : </h5>
                        <p class="card-text">Session disponible le <br> {{ session.date|date('d/m/Y à H:i' , 'Europe/Paris') }}h </p>
                        {% if session == app.user.session %}
                            <a href="{{ path('session_revoke', {'id' : session.id}) }}" class="btn btn-primary"> Se
                                désister </a>
                        {% else %}
                            {% if app.user.backgroundUrl %}
                                <a  href="{{ path('session_inscription', {'id' : session.id}) }}" class="btn btn-primary " id="btn_inscription">S'inscrire
                                    ({{ session.user|length ~ '/' ~  session.nbplace }} inscrits)
                                </a>
                            {% else %}
                                <a type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                                    Envoyer son background
                                </a>
                            {% endif %}

                        {% endif %}
                        {% if "ROLE_ADMIN" in app.user.roles %}
                            <a href="{{ path('session_list_users',{'id' : session.id}) }}" class="btn btn-primary">Voir
                                les
                                utilisateurs</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Envoyer son background</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="{{ path('session_sendBackground') }}" method="post">
                    <div class="modal-body">
                        <p>Avant de pouvoir s'inscrire à une session, il vous faut envoyer votre background
                        en format URL Google Document.
                            <a href="https://www.google.fr/intl/fr/docs/about/"><i>Cliquez ici </i></a>
                            pour faire un google doc
                        </p>
                            <label for="input_background_url" >URL : </label>
                            <input type="text" id="input_background_url" placeholder="https://docs.google.com/document/....." style="width: 400px" onchange="verify()" name="background_url">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" id="btn_modal_close" data-bs-dismiss="modal">Fermer</button>
                        <button type="submit" class="btn btn-primary" id="btn_modal_send">Envoyer</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>
        <!-- Modal -->
    {% else %}
        <div>
            Vous devez lier votre compte discord pour vous inscrire à une session !
            <a href="{{ path('user_profile_discord_link') }}">Lier son compte discord ! </a>
        </div>
    {% endif %}
    <script src="{{ asset('assets/js/script_session_list.js') }}"></script>
{% endblock %}
{% block javascripts %}
    {{ parent() }}
{% endblock %}

templates/session/edit.html.twig
{% extends 'main/index.html.twig' %}

{% block title %}Edit Session{% endblock %}

{% block content %}
    <h1>Edit Session</h1>

    {{ include('session/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('session_index') }}">back to list</a>

    {{ include('session/_delete_form.html.twig') }}
{% endblock %}

templates/session/index.html.twig
{% extends 'main/index.html.twig' %}

{% block title %}Session index{% endblock %}

{% block content %}
    <h1>Session index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Nombre de place</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for session in sessions %}
            <tr>
                <td>{{ session.id }}</td>
                <td>{{ session.date ? session.date|date('d/m/Y - H:i') : '' }}</td>
                <td>{{ session.nbPlace }}</td>
                <td>
                    <a href="{{ path('session_show', {'id': session.id}) }}" class="btn_tabs">Détails</a>
                    <a href="{{ path('session_edit', {'id': session.id}) }}" class="btn_tabs">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">Aucunes sessions trouvées</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('session_new') }}" class="btn btn_form">Nouvelle session</a>
{% endblock %}

templates/session/new.html.twig
{% extends 'main/index.html.twig' %}

{% block title %}New Session{% endblock %}

{% block content %}
    <h1>Create new Session</h1>

    {{ include('session/_form.html.twig') }}

    <a href="{{ path('session_index') }}">back to list</a>
{% endblock %}

templates/session/show.html.twig
{% extends 'main/index.html.twig' %}

{% block title %}Session{% endblock %}

{% block content %}
    <a href="{{ path('session_index') }}"><i class='bx bx-left-arrow-alt arrow_back'></i></a>
    <h1>Session</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ session.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ session.date ? session.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Nb_place</th>
                <td>{{ session.nbPlace }}</td>
            </tr>
        </tbody>
    </table>



    <a href="{{ path('session_edit', {'id': session.id}) }}" class="btn btn_form">edit</a>

    {{ include('session/_delete_form.html.twig') }}
{% endblock %}

templates/session/user_history.html.twig
{% extends 'main/index.html.twig' %}

{% block title %}Réponses : {% endblock %}
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('assets/css/styleMainQcm.css') }}">
{% endblock %}

{% block content %}
    {% set i = 1 %}
    {% for question in questions %}
        <ul>
{#            {% set idQuestion = [] %}#}
{#            {% set idQuestion = idQuestion|merge([history.response.question.id]) %}#}

            {% if question.countCorrect() > 1 %}
                <h4 id="title_question">Q.{{ i }} - {{ question.label }}  (contient plusieurs bonnes réponses)</h4>

            {% else %}
                <h4 id="title_question">Q.{{ i }} - {{ question.label }}</h4>

            {% endif %}
            {% for reponse in question.reponses %}
                {% set correct = reponse.isCorrect %}

                {% if question.countCorrect() > 1 %}
                    {% set isAnswered = (histories[question.id][reponse.id]).response.id is defined and (histories[question.id][reponse.id]).response.id == reponse.id %}
                    {# checkbox #}
                    <div class="checkboxResp spacing_rep">
                        <input type="checkbox"
                           class="checkbox_input" disabled
                        {% if isAnswered %}
                            checked
                        {% endif %}
                        >
                        <label  class="
                                {% if correct %}
                                    correct_input
                                {% endif %}
                                {% if isAnswered and correct %}
                                    correct_response
                                {% endif %}
                                {% if isAnswered and not correct %}
                                    bad_response
                                {% endif %}
                                "
                        >
                            &nbsp;&nbsp;{{ reponse.label }}
                        </label>
                    </div>
                {% else %}
                    {% set isAnswered = histories[question.id].response.id == reponse.id %}
                    {# radiobutton #}
                    {% if answers['response_radio_' ~ question.id ] is defined and answers['response_radio_' ~ question.id] == reponse.id %}
                        {% set checked = 'checked' %}
                    {% endif %}

                    <div class="radioResp spacing_rep">
                        <input type="radio"
                                class="radio_input" disabled
                                {% if isAnswered %}
                                    checked
                                {% endif %}

                        >
                        <label for="response_radio_{{ reponse.id }}" class="
                                {% if correct %}
                                    correct_input
                                {% endif %}
                                {% if isAnswered and correct %}
                                    correct_response
                                {% endif %}
                                {% if isAnswered and not correct %}
                                    bad_response
                                {% endif %}
                                "
                        >
                            &nbsp; &nbsp;{{ reponse.label }}
                        </label>
                    </div>
                {% endif %}
            {% else %}
                <span class="spacing_rep"> Cette question n'a pas de réponse</span>
            {% endfor %}

        </ul>
        {% set i = i + 1  %}
    {% endfor %}

{% endblock %}