src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"username"}, message="There is already an account with this username")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="date")
     */
    private $birth_date;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tokenMail;

    /**
     * @ORM\Column(type="integer" , nullable=true)
     */
    private $fail;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $last_attempt;

    /**
     * @ORM\Column(type="string",length=450 ,nullable=true)
     */
    private $discord_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tokenDiscord;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $nb_try;

    /**
     * @ORM\ManyToOne(targetEntity=Session::class, inversedBy="user")
     */
    private $session;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $imgDiscord;

    /**
     * @ORM\OneToOne(targetEntity=History::class, mappedBy="user", cascade={"persist", "remove"})
     */
    private $history;

    /**
     * @ORM\OneToMany(targetEntity=History::class, mappedBy="user")
     */
    private $histories;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $username_discord;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $comment;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Admis;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $background_url;

    public function __construct()
    {
        $this->histories = new ArrayCollection();
    }




    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birth_date;
    }

    public function setBirthDate(\DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getTokenMail(): ?string
    {
        return $this->tokenMail;
    }

    public function setTokenMail(?string $tokenMail): self
    {
        $this->tokenMail = $tokenMail;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFail()
    {
        return $this->fail;
    }

    /**
     * @param mixed $fail
     */
    public function setFail($fail): void
    {
        $this->fail = $fail;
    }


    public function getLastAttempt(): ?\DateTimeInterface
    {
        return $this->last_attempt;
    }

    public function setLastAttempt(?\DateTimeInterface $last_attempt): self
    {
        $this->last_attempt = $last_attempt;

        return $this;
    }

    public function getDiscordId(): ?string
    {
        return $this->discord_id;
    }

    public function setDiscordId(?string $discord_id): self
    {
        $this->discord_id = $discord_id;

        return $this;
    }

    public function getTokenDiscord(): ?string
    {
        return $this->tokenDiscord;
    }

    public function setTokenDiscord(?string $tokenDiscord): self
    {
        $this->tokenDiscord = $tokenDiscord;

        return $this;
    }

    public function getNbTry(): ?int
    {
        return $this->nb_try;
    }

    public function setNbTry(?int $nb_try): self
    {
        $this->nb_try = $nb_try;

        return $this;
    }

    /**
     * @return bool
     */
    public function canParticipate(): bool
    {
        $atmDate = new \DateTime('now');
        if($this->getLastAttempt() != null){
            $lastAttempt = clone $this->getLastAttempt();
            return date_modify($lastAttempt,'+ 24 hours') < $atmDate;
        }
        return true;
    }

    public function getSession(): ?Session
    {
        return $this->session;
    }

    public function setSession(?Session $session): self
    {
        $this->session = $session;

        return $this;
    }

    public function getImgDiscord(): ?string
    {
        return $this->imgDiscord;
    }

    public function setImgDiscord(?string $imgDiscord): self
    {
        $this->imgDiscord = $imgDiscord;

        return $this;
    }
    public function canSignupToSession(){
        $countBadResponses = 0;
        foreach ($this->getHistories() as $history) {
            if (!$history->getResponse()->getIsCorrect()) {
                $countBadResponses++;
            }
        }
        return $countBadResponses <= 3;
    }

    /**
     * @return Collection|History[]
     */
    public function getHistories(): Collection
    {
        return $this->histories;
    }

    public function addHistory(History $history): self
    {
        if (!$this->histories->contains($history)) {
            $this->histories[] = $history;
            $history->setUser($this);
        }

        return $this;
    }

    public function removeHistory(History $history): self
    {
        if ($this->histories->removeElement($history)) {
            // set the owning side to null (unless already changed)
            if ($history->getUser() === $this) {
                $history->setUser(null);
            }
        }

        return $this;
    }

    public function getUsernameDiscord(): ?string
    {
        return $this->username_discord;
    }

    public function setUsernameDiscord(?string $username_discord): self
    {
        $this->username_discord = $username_discord;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getAdmis(): ?bool
    {
        return $this->Admis;
    }

    public function setAdmis(?bool $Admis): self
    {
        $this->Admis = $Admis;

        return $this;
    }

    public function getBackgroundUrl(): ?string
    {
        return $this->background_url;
    }

    public function setBackgroundUrl(?string $background_url): self
    {
        $this->background_url = $background_url;

        return $this;
    }

}

src/Controller/UserProfileController.php
<?php

namespace App\Controller;

use App\Form\ModifyPasswordType;
use App\Repository\SessionRepository;
use App\Services\ServicesDiscord;
use Doctrine\ORM\EntityManagerInterface;
use League\OAuth2\Client\Provider\Exception\IdentityProviderException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use function Symfony\Component\Translation\t;

class UserProfileController extends AbstractController
{

    /**
     * @Route("/profile", name="user_profile")
     */
    public function modifyPassword(Request $request, UserPasswordHasherInterface $passwordEncoder, EntityManagerInterface $em, SessionInterface $session) : Response {

        if(isset($_GET['code'])) {
            $session->set('discord_code', $_GET['code']);
            return $this->redirectToRoute('user_profile');
        }
        $user = $this->getUser();
        $formModif = $this->createForm(ModifyPasswordType::class);

        $formModif->handleRequest($request);

        if($formModif->isSubmitted() && $formModif->isValid()){
            $newPassword = $formModif->getData()['newPassword'];
            $oldPassword = $formModif->getData()['password'];

            if($passwordEncoder->isPasswordValid($user,$oldPassword)){
                $hashPassword = $passwordEncoder->hashPassword($user,$newPassword);
                $user->setPassword($hashPassword);
                $em->flush();
                $this->addFlash('success',"Votre mot de passe a été changé avec succès");
                return $this->redirectToRoute('user_profile');
            }else{
                $this->addFlash('error', 'Votre ancien mot de passe ne correspond à celui que vous avez rentré.');
            }
        }

        if($session->get('discord_code')) {
            $code = $session->get('discord_code');
            $dsOauthProvider = new ServicesDiscord();
            $session->remove('discord_code');
            try {
                $token = $dsOauthProvider->tryGetToken($code);
                $userInfos = $dsOauthProvider->getUserInfos($token['access_token']);
                $user->settokenDiscord($token['access_token']);
                $user->setUsernameDiscord($userInfos['username'].'#'.$userInfos['discriminator']);
                $user->setimgDiscord($userInfos['avatar']);
                $user->setDiscordId($userInfos['id']);
                $em->flush();
                $this->addFlash('success', 'Compte lié à discord avec succès !');
                $this->redirectToRoute('user_profile');
            } catch (IdentityProviderException $e) {
                dump($e->getMessage());
            }
        }

        return $this->renderForm('user_profile/index.html.twig',['formModif' => $formModif]);
    }

    /**
     * @Route("/profile/link", name="user_profile_discord_link")
     */
    public function linkDiscord(EntityManagerInterface $em) : Response{
        $provider = new \Wohali\OAuth2\Client\Provider\Discord([
            'clientId' => $_SERVER['DISCORD_CLIENT_ID'],
            'clientSecret' => $_SERVER['DISCORD_CLIENT_SECRET'],
            'redirectUri' => $_SERVER['DISCORD_REDIRECT_URI']
        ]);
        $authUrl = $provider->getAuthorizationUrl([
            'scope' => ['identify']
        ]);
        // && $this->getUser()->getDiscordId() == null && $this->getUser()->gettokenDiscord() == null

        return $this->redirect($authUrl);
    }

    /**
     * @Route ("/profile/discord/revoke" , name="profile_revoke_discord")
     */
    public function revokeTokenDiscord( EntityManagerInterface $em, ServicesDiscord $sd, SessionInterface $session) :Response{
        if ($this->getUser()->getSession() !== null) {
            $this->addFlash('warning', 'Vous êtes inscrit a une session');
            return $this->redirectToRoute('user_profile');
        }

        if($this->getUser()->getDiscordId() != null && $this->getUser()->gettokenDiscord() != null){
            $revokeURL = 'https://discordapp.com/api/oauth2/token/revoke';
            $sd->logout($revokeURL,array(
                'token' => $this->getUser()->getTokenDiscord(),
                'token_type_hint' => 'access_token',
                'clientId' => '920981831384440843',
                'client_secret' => 'ablnGro0-LICBWQX67JpVtb3iHVGOHMv'
            ));
            $this->getUser()->setDiscordId(null);
            $this->getUser()->settokenDiscord(null);
            $this->getUser()->setImgDiscord(null);
            $this->getUser()->setUsernameDiscord(null);
            $session->remove('discord_code');
            $em->flush();
            $this->addFlash('success','Compte discord délié avec succès');

        }
        return $this->redirectToRoute('user_profile');
    }
}

templates/user_profile/index.html.twig
{% extends 'main/index.html.twig' %}

{% block title %}Gestion du profil {{ app.user.username }}{% endblock %}

{% block stylesheets %}
    {{ parent() }}

{% endblock %}
    {% block content %}
        <div class="container">
            {% for message in app.flashes('success') %}
                <div class="flash-success">
                    {{ message }}
                </div>
            {% endfor %}
            {% for message in app.flashes('warning') %}
                <div class="flash-success">
                    <img src="https://c.tenor.com/iPPLJM-iQ-8AAAAC/julien-lepers-c-est-non.gif" height="100px" alt="">
                    {{ message }}
                </div>
            {% endfor %}

            <h1>Gestion de compte</h1>
            <div class="container">
                <label for="pseudo">Pseudo : </label>
                <input type="text" id="pseudo" disabled value="{{ app.user.username }}">
                <br>
                <label for="dateOfBirth">Date de naissance : </label>
                <input type="text" id="dateOfBirth" disabled value="{{ app.user.birthDate|date('d/m/Y') }}">
                <br>
                <label for="email">E-mail : </label>
                <input type="text" id="emailInput" disabled value="{{ app.user.email }}">
                <span id="iconEmail" style="cursor: pointer"><i  class="far fa-eye" onclick="show_email()"></i></span>
                <br>
                <label for="last_attempt">Dernier essai : </label>
                <input type="text" id="last_attempt" disabled value="{{ app.user.lastAttempt|date('d/m/Y h:m:s') }}">
            </div>
            <div class="container">
                <div class="discord-link">
                    {% for message in app.flashes('success') %}
                        <div class="alert alert-success">
                            {{ message }}
                        </div>
                    {% endfor %}
                    {% if not app.user.discordId %}
                        <a href="{{ path('user_profile_discord_link') }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                                <g fill="none" fill-rule="evenodd">
                                    <g fill="#7289DA" fill-rule="nonzero">
                                        <g>
                                            <g>
                                                <g>
                                                    <g>
                                                        <g>
                                                            <path d="M8.328 10.068c-.684 0-1.224.6-1.224 1.332 0 .732.552 1.332 1.224 1.332.684 0 1.224-.6 1.224-1.332.012-.732-.54-1.332-1.224-1.332zm4.38 0c-.684 0-1.224.6-1.224 1.332 0 .732.552 1.332 1.224 1.332.684 0 1.224-.6 1.224-1.332 0-.732-.54-1.332-1.224-1.332z" transform="translate(-894 -1312) translate(420 158) translate(0 1092) translate(410 48) translate(64 14) translate(1.5)"/>
                                                            <path d="M18.54 0H2.46C1.104 0 0 1.104 0 2.472v16.224c0 1.368 1.104 2.472 2.46 2.472h13.608l-.636-2.22 1.536 1.428 1.452 1.344L21 24V2.472C21 1.104 19.896 0 18.54 0zm-4.632 15.672s-.432-.516-.792-.972c1.572-.444 2.172-1.428 2.172-1.428-.492.324-.96.552-1.38.708-.6.252-1.176.42-1.74.516-1.152.216-2.208.156-3.108-.012-.684-.132-1.272-.324-1.764-.516-.276-.108-.576-.24-.876-.408-.036-.024-.072-.036-.108-.06-.024-.012-.036-.024-.048-.036-.216-.12-.336-.204-.336-.204s.576.96 2.1 1.416c-.36.456-.804.996-.804.996-2.652-.084-3.66-1.824-3.66-1.824 0-3.864 1.728-6.996 1.728-6.996 1.728-1.296 3.372-1.26 3.372-1.26l.12.144c-2.16.624-3.156 1.572-3.156 1.572s.264-.144.708-.348c1.284-.564 2.304-.72 2.724-.756.072-.012.132-.024.204-.024.732-.096 1.56-.12 2.424-.024 1.14.132 2.364.468 3.612 1.152 0 0-.948-.9-2.988-1.524l.168-.192s1.644-.036 3.372 1.26c0 0 1.728 3.132 1.728 6.996 0 0-1.02 1.74-3.672 1.824z" transform="translate(-894 -1312) translate(420 158) translate(0 1092) translate(410 48) translate(64 14) translate(1.5)"/>
                                                        </g>
                                                    </g>
                                                </g>
                                            </g>
                                        </g>
                                    </g>
                                </g>
                            </svg>
                            Lier son compte discord
                        </a>
                    {% else %}
                        <div>
                            <a href="{{ path('profile_revoke_discord') }}">
                                Délier son compte Discord
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
            <div>
                <h4>Changer de mot de passe</h4>
                {{ form_start(formModif) }}
                {{ form_widget(formModif) }}
                {% for message in app.flashes('error') %}
                    <div class="flash-error">
                        {{ message }}
                    </div>
                {% endfor %}
                <button class="btn btn-primary">Modifier mon mot de Passe</button>
                {{ form_end(formModif) }}
            </div>
        </div>
        <script src="{{ asset('assets/js/my_profil_script.js') }}">
        </script>
        {% endblock %}
        {% block javascripts %}
            {{ parent() }}
        {% endblock %}